events {}

http {
    server {
        listen 80;

        # Python Merchant Backend
        location /merchant-be/ {
            # The trailing slash indicates we want Nginx to strip the "/merchant-be" 
            # prefix before sending traffic internally to FastAPI's port 10000
            proxy_pass http://washli-be-container:10000/;
            
            # Forward headers so logs show the real IP, not Nginx's Docker IP
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Any future Quarkus Apps can just go right here below the python one!
        # location /quarkus-app/ {
        #     proxy_pass http://quarkus-container:8080/;
        #     proxy_set_header Host $host;
        # }
    }
}
